apiVersion: batch/v1
kind: Job
metadata:
  name: gen3c-test-single-image-rendering-pixel-focus
spec:
  template:
    metadata:
      name: gen3c-test-single-image-rendering-pixel-focus
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-SXM4-80GB
      restartPolicy: Never
      containers:
      - name: python-container
        image: python:3.10
        command: [ "/bin/bash", "-c" ]
        args:
        - |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential libc6-dev git wget pkg-config ca-certificates \
            libgl1 libglib2.0-0 
          rm -rf /var/lib/apt/lists/*

          curl -fsSL https://pixi.sh/install.sh | bash
          export PATH="/root/.pixi/bin:$PATH"
          export PIXI_HOME="/root/.pixi"

          cd /data-world-model/world-models/GEN3C-Project
          pixi install 
          pixi run install-all-deps
          pixi run copy-custom

          pixi run run-render_only_pixel_focus_test


        resources:
          limits:
            nvidia.com/a100: 1
            cpu: "4"  # Maximum CPU usage
            memory: "120G"  # Maximum memory usage
          requests:
            nvidia.com/a100: 1
            cpu: "4"  # Minimum CPU allocation
            memory: "100G"  # Minimum memory allocation
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: amir-pvc-videocompression
          - mountPath: /data-world-model
            name: amir-pvc-world-model
      volumes:
      - name: amir-pvc-videocompression
        persistentVolumeClaim:
          claimName: amir-pvc-videocompression
      - name: amir-pvc-world-model
        persistentVolumeClaim:
          claimName: amir-pvc-world-model
      - name: dshm
        emptyDir:     
          medium: Memory
  backoffLimit: 0
