apiVersion: batch/v1
kind: Job
metadata:
  name: gen3c-test-diffusion-only
spec:
  template:
    metadata:
      name: gen3c-test-diffusion-only
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-SXM4-80GB
      restartPolicy: Never
      containers:
      - name: python-container
        image: python:3.10
        command: [ "/bin/bash", "-c" ]
        args:
        - |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential libc6-dev git wget pkg-config ca-certificates \
            libgl1 libglib2.0-0 
          rm -rf /var/lib/apt/lists/*

          curl -fsSL https://pixi.sh/install.sh | bash
          export PATH="/root/.pixi/bin:$PATH"
          export PIXI_HOME="/root/.pixi"

          cd /data-world-model/world-models/GEN3C-Project
          pixi install 
          pixi run install-all-deps
          pixi run copy-custom 

          # pixi run run_diffusion_only_generic -- \
          # --vipe_path ../PoseDepthEstimation/vipe_results \
          # --rendered_images_path rendered_warp_images_vipe_zoom_out.pt \
          # --rendered_masks_path rendered_warp_masks_vipe_zoom_out.pt \
          # --video_save_name test_diffusion_only_vipe_zoomout \
          # --guidance 1 \
          # --prompt "" \
          # --save_buffer

          # pixi run run_diffusion_only_generic -- \
          # --input_image_path drone_samples/test_004/_1734644976.704000.jpg \
          # --rendered_images_path multiview_warp_images_source_to_target.pt \
          # --rendered_masks_path multiview_warp_masks_source_to_target.pt \
          # --video_save_name test_diffusion_only_multiview_source_to_target \
          # --guidance 1 \
          # --prompt "" \
          # --save_buffer

          # pixi run run_diffusion_only_generic -- \
          # --input_image_path ../VGGT-Project/test_004_result/images/_1734644976.704000.jpg \
          # --rendered_images_path vggt_multiview_warp_images_source_to_target.pt \
          # --rendered_masks_path vggt_multiview_warp_masks_source_to_target.pt \
          # --video_save_name test_diffusion_only_vggt_source_to_target \
          # --guidance 1 \
          # --prompt "" \
          # --save_buffer

          pixi run run_diffusion_only_generic -- \
          --input_image_path drone_samples/test_008/images/1.png \
          --rendered_images_path waymo_multiview_warp_images_source_to_target_lidar.pt \
          --rendered_masks_path waymo_multiview_warp_masks_source_to_target_lidar.pt \
          --video_save_name test_diffusion_only_waymo_source_to_target_lidar \
          --guidance 1 \
          --prompt "" \
          --save_buffer

          pixi run run_diffusion_only_generic -- \
          --input_image_path drone_samples/test_008/images/1.png \
          --rendered_images_path waymo_multiview_warp_images_source_to_target.pt \
          --rendered_masks_path waymo_multiview_warp_masks_source_to_target.pt \
          --video_save_name test_diffusion_only_waymo_source_to_target \
          --guidance 1 \
          --prompt "" \
          --save_buffer

        resources:
          limits:
            nvidia.com/a100: 1
            cpu: "4"  # Maximum CPU usage
            memory: "120G"  # Maximum memory usage
          requests:
            nvidia.com/a100: 1
            cpu: "4"  # Minimum CPU allocation
            memory: "100G"  # Minimum memory allocation
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: amir-pvc-videocompression
          - mountPath: /data-world-model
            name: amir-pvc-world-model
      volumes:
      - name: amir-pvc-videocompression
        persistentVolumeClaim:
          claimName: amir-pvc-videocompression
      - name: amir-pvc-world-model
        persistentVolumeClaim:
          claimName: amir-pvc-world-model
      - name: dshm
        emptyDir:     
          medium: Memory
  backoffLimit: 0
